##### 2. Каждая строка в файле соответствует одному предложению. Считайте их, приведите каждую к нижнему регистру с помощью строковой функции lower().

In [2]:
file_obj = open("D:\Programms\Anaconda2\sentences.txt") # открыли исходный файл

In [3]:
with open("D:\Programms\Anaconda2\sentences2.txt", 'w') as file2:
    for line in file_obj:
        file2.write(line.lower().strip()) # записали в новый файл содержимое исходного, приведя весь текст к нижнему регистру
        """ 
        Делаю strip() на тот случай, когда надо будет в пункте 3 произведить токенизацию
        и удалять пустые слова после разделения.
        Иначе может получиться некорректная ситуация (не для данного текстового файла):
            'n' одновременно является "остатком" от '\n' и "обычной" буквой текста. 
        """

In [4]:
file2 = open("D:\Programms\Anaconda2\sentences2.txt")

file2.read() # проверили, что все сработало правильно

'in comparison to dogs, cats have not undergone major changes during the domestication process.as cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.a common interactive use of cat for a single file is to output the content of a file to standard output.cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.in one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.the domesticated cat and its closest wild ancestor are both diploid organisms that possess 38 chromosomes and roughly 20,000 genes.domestic cats are similar in size to the other members of the genus felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).however, if the output is piped or redirected, cat is unnecessary.cat with one named file is safer where human error is a concern - one wrong use of the defaul

#### 3. Произведите токенизацию, то есть разбиение текстов на слова. Для этого можно воспользоваться регулярным выражением, которое считает разделителем любой символ, не являющийся буквой: re.split('[^a-z]', t). Не забудьте удалить пустые слова после разделения.

In [5]:
file2 = open("D:\Programms\Anaconda2\sentences2.txt") # открыли файл, чтобы использовать readlines
file_string = str(file2.readlines()) # преобразуем список строк в строку (это требуется для split)

# самопроверка
print file_string 
type(file_string)

['in comparison to dogs, cats have not undergone major changes during the domestication process.as cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.a common interactive use of cat for a single file is to output the content of a file to standard output.cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.in one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.the domesticated cat and its closest wild ancestor are both diploid organisms that possess 38 chromosomes and roughly 20,000 genes.domestic cats are similar in size to the other members of the genus felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).however, if the output is piped or redirected, cat is unnecessary.cat with one named file is safer where human error is a concern - one wrong use of the defau

str

In [6]:
import re # для re.split
splitted = re.split('[^a-z]', file_string) # разбиение текстов на слова
print splitted
type (splitted)

['', '', 'in', 'comparison', 'to', 'dogs', '', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process', 'as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', '', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', '', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes', 'a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output', 'cats', 'can', 'hear', 'sounds', 'too', 'faint', 'or', 'too', 'high', 'in', 'frequency', 'for', 'human', 'ears', '', 'such', 'as', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals', 'in', 'one', '', 'people', 'deliberately', 'tamed', 'cats', 'in', 'a', 'process', 'of', 'artificial', 'selection', '', 'as', 'they', 'were', 'useful', 'predators', 'of', 'vermin', 'the', 'domesticated', 'cat', 'and', 'its', 'closest', 'wild', 'ancestor', 'are', 'both',

list

In [7]:
splitted = [x for x in splitted if x != ''] # удаление пробельных символов

In [8]:
print splitted

['in', 'comparison', 'to', 'dogs', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process', 'as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes', 'a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output', 'cats', 'can', 'hear', 'sounds', 'too', 'faint', 'or', 'too', 'high', 'in', 'frequency', 'for', 'human', 'ears', 'such', 'as', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals', 'in', 'one', 'people', 'deliberately', 'tamed', 'cats', 'in', 'a', 'process', 'of', 'artificial', 'selection', 'as', 'they', 'were', 'useful', 'predators', 'of', 'vermin', 'the', 'domesticated', 'cat', 'and', 'its', 'closest', 'wild', 'ancestor', 'are', 'both', 'diploid', 'organisms', 'that',

#### 4. Составьте список всех слов, встречающихся в предложениях. Сопоставьте каждому слову индекс от нуля до (d - 1), где d — число различных слов в предложениях. Для этого удобно воспользоваться структурой dict.

In [9]:
'''Функция List_of_all_words составляет список всех слов, встречающихся в предложениях.

List - исходный список;
word - элемент списка List;
new_list - список всех слов, встречающихся в предложениях.''' 

def List_of_all_words(List):
    new_list = []
    for word in List:
        if word not in new_list:
            new_list.append(word)
    return new_list

In [10]:
# Применим функцию List_of_all_words к списку splitted.
splitted = List_of_all_words(splitted)
print splitted

['in', 'comparison', 'to', 'dogs', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process', 'as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', 'it', 'can', 'be', 'also', 'used', 'concatenate', 'binary', 'files', 'where', 'will', 'just', 'sequence', 'a', 'common', 'interactive', 'use', 'for', 'single', 'file', 'is', 'output', 'content', 'standard', 'hear', 'sounds', 'too', 'faint', 'or', 'high', 'frequency', 'human', 'ears', 'such', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals', 'one', 'people', 'deliberately', 'tamed', 'artificial', 'selection', 'they', 'were', 'useful', 'predators', 'vermin', 'domesticated', 'its', 'closest', 'wild', 'ancestor', 'are', 'both', 'diploid', 'organisms', 'that', 'possess', 'chromosomes', 'roughly', 'genes', 'domestic', 'similar', 'size', 'members', 'genus', 'felis', 'typically', 'weighing', 'between', 'kg', 'lb', 'however', 'if', 'piped', 'redirected', 'unnecessary', 'with', 'named

In [11]:
d = len(splitted) # число различных слов в предложениях
keys = [x for x in range(0, d)] # создаем лист ключей
print keys

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

In [12]:
dictionary = dict(zip(keys, splitted)) # сопоставим каждому слову индекс
print dictionary

{0: 'in', 1: 'comparison', 2: 'to', 3: 'dogs', 4: 'cats', 5: 'have', 6: 'not', 7: 'undergone', 8: 'major', 9: 'changes', 10: 'during', 11: 'the', 12: 'domestication', 13: 'process', 14: 'as', 15: 'cat', 16: 'simply', 17: 'catenates', 18: 'streams', 19: 'of', 20: 'bytes', 21: 'it', 22: 'can', 23: 'be', 24: 'also', 25: 'used', 26: 'concatenate', 27: 'binary', 28: 'files', 29: 'where', 30: 'will', 31: 'just', 32: 'sequence', 33: 'a', 34: 'common', 35: 'interactive', 36: 'use', 37: 'for', 38: 'single', 39: 'file', 40: 'is', 41: 'output', 42: 'content', 43: 'standard', 44: 'hear', 45: 'sounds', 46: 'too', 47: 'faint', 48: 'or', 49: 'high', 50: 'frequency', 51: 'human', 52: 'ears', 53: 'such', 54: 'those', 55: 'made', 56: 'by', 57: 'mice', 58: 'and', 59: 'other', 60: 'small', 61: 'animals', 62: 'one', 63: 'people', 64: 'deliberately', 65: 'tamed', 66: 'artificial', 67: 'selection', 68: 'they', 69: 'were', 70: 'useful', 71: 'predators', 72: 'vermin', 73: 'domesticated', 74: 'its', 75: 'closes

#### 5. Создайте матрицу размера n * d, где n — число предложений. Заполните ее: элемент с индексом (i, j) в этой матрице должен быть равен количеству вхождений j-го слова в i-е предложение. У вас должна получиться матрица размера 22 * 254.

In [13]:
# Подсчет количества предложений в тексте.
with open("D:\Programms\Anaconda2\sentences.txt", 'r') as file_obj:
    List_to_string = ''.join(file_obj.readlines()) # преобразуем содержимое файла в одну строку
n = dots = List_to_string.count('.\n') # кол-во предложений в тексте - это количество точек вида .\n

In [14]:
print n
print List_to_string

22
In comparison to dogs, cats have not undergone major changes during the domestication process.
As cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.
A common interactive use of cat for a single file is to output the content of a file to standard output.
Cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.
In one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.
The domesticated cat and its closest wild ancestor are both diploid organisms that possess 38 chromosomes and roughly 20,000 genes.
Domestic cats are similar in size to the other members of the genus Felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).
However, if the output is piped or redirected, cat is unnecessary.
cat with one named file is safer where human error is a concern - one wrong use of 

In [15]:
import numpy as np

In [16]:
matrix = np.zeros((n, d)) # матрица размера n * d

In [17]:
# Перезапишем файл sentences2.txt.
file_obj = open("D:\Programms\Anaconda2\sentences.txt") # открыли исходный файл
with open("D:\Programms\Anaconda2\sentences2.txt", 'w') as file2:
    for line in file_obj:
        file2.write(line.lower())
file_obj.close()

file2 = open("D:\Programms\Anaconda2\sentences2.txt") # открыли файл, чтобы использовать readlines
file_list = file2.readlines() # получаем список строк

#самопроверка
print file_list
type(file_list)

['in comparison to dogs, cats have not undergone major changes during the domestication process.\n', 'as cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.\n', 'a common interactive use of cat for a single file is to output the content of a file to standard output.\n', 'cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.\n', 'in one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.\n', 'the domesticated cat and its closest wild ancestor are both diploid organisms that possess 38 chromosomes and roughly 20,000 genes.\n', 'domestic cats are similar in size to the other members of the genus felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).\n', 'however, if the output is piped or redirected, cat is unnecessary.\n', 'cat with one named file is safer where human

list

In [18]:
# Заполнияем матрицу.
for i in range(0, n):                # i-ое предложение
    for j in range(0, d):            # j-ый ключ слова в dictionary
        matrix[i][j] = file_list[i].count(dictionary[j])

In [19]:
print matrix

[[2. 1. 1. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [2. 0. 2. ... 0. 0. 0.]
 ...
 [3. 0. 0. ... 0. 0. 0.]
 [4. 0. 1. ... 0. 0. 0.]
 [2. 0. 1. ... 1. 1. 1.]]


#### 6. Найдите косинусное расстояние от предложения в самой первой строке (In comparison to dogs, cats have not undergone...) до всех остальных с помощью функции scipy.spatial.distance.cosine. Какие номера у двух предложений, ближайших к нему по этому расстоянию (строки нумеруются с нуля)? Эти два числа и будут ответами на задание. Само предложение (In comparison to dogs, cats have not undergone... ) имеет индекс 0.

In [20]:
from scipy.spatial.distance import cosine

In [21]:
cos_array = [] # список, содержащий косинусные расстояния
for i in range(1, n):     # i - строки матрицы matrix #начинаем с 1(с 0 будет сравнение первой строки самой с собой)
    cos_array.append(cosine(matrix[0], matrix[i])) # добавление расстояния в список cos_array

In [22]:
# самопроверка
print cos_array
print type (cos_array)
print len(cos_array)

[0.11657075758219448, 0.19777738803029532, 0.15996056399532876, 0.10555511876381107, 0.14004527051866666, 0.15026685747694313, 0.20609040268280376, 0.12477127763327134, 0.16341484965019626, 0.189873417721519, 0.16967762387371021, 0.18850982361052293, 0.132601041976097, 0.1508719887668445, 0.1756063450112042, 0.12164187392382353, 0.17323261808567447, 0.14123976674418737, 0.18543183904737315, 0.12750373890975997, 0.1628326195551163]
<type 'list'>
21


In [23]:
# Cоздадим объект copy_cos_arr такой же как объект cos_array.
import copy
copy_cos_arr = copy.deepcopy(cos_array)
copy_cos_arr.sort() # отсортируем список copy_cos_arr
print copy_cos_arr

[0.10555511876381107, 0.11657075758219448, 0.12164187392382353, 0.12477127763327134, 0.12750373890975997, 0.132601041976097, 0.14004527051866666, 0.14123976674418737, 0.15026685747694313, 0.1508719887668445, 0.15996056399532876, 0.1628326195551163, 0.16341484965019626, 0.16967762387371021, 0.17323261808567447, 0.1756063450112042, 0.18543183904737315, 0.18850982361052293, 0.189873417721519, 0.19777738803029532, 0.20609040268280376]


In [24]:
# Номера двух предложений.
print cos_array.index(0.10555511876381107) + 1
print cos_array.index(0.11657075758219448) + 1

4
1
